### ISSUE TITLE
Is there an error here ?

### ISSUE THREAD

**Issue by PhilippeCorreges** [mean-expert-official/sdk-builder-starter#4]
Ran a npm install in both folders.
Started the api server and when I did a ng serve on client side folder I got : 
### ->ng serve
Cannot find module './models/config'
Error: Cannot find module './models/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/IOSoftwareSAS/WebstormProjects/sdk-builder-starter/project-app/node_modules/angular-cli/addon/ng2/index.js:4:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by PhilippeCorreges** [comment]
Sorry I did not generate the client sdk.

Working fine for me. Very happy to have this for now.
You can close this issue.

Thanks and Regards

**Comment by jonathan-casarrubias** [comment]
Hey @PhilippeCorreges I'm glad you found the issue 👍 

Cheers
Jon

**Comment by portokallidis** [comment]
Hi! 
I am having the same although i did generate the client sdk.
Here is what i did:
- installed angular-cli globally
- npm install on both directories
- cd project-api && npm run build:sdk && npm start
``Generating "sdk" for the API endpoint "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed 
via remoting. The Angular code for this scope won't be generated.
Removing base directory /home/nporto/sdk-builder-starter/project-app/src/app/shared/sdk
LoopBack SDK Builder: adding User model to SDK
Generating:.....
Enjoy!!!
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer``

- cd project-app && ng serve
And got this again:
``Cannot find module './models/config'``


I am sure that i missed something..
I really want to try this project :D

**Comment by PhilippeCorreges** [comment]
Hello @portokallidis 
I guess this is just a folder story.
Check all your paths. The code editor completion will help you with it.
